# Generated by Django 2.2 on 2020-06-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr_buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='traveler',
            new_name='travels',
        ),
    ]
