# Generated by Django 2.2 on 2020-06-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tr_buddy_app', '0002_auto_20200619_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='travels',
            new_name='travels_by',
        ),
    ]
